In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [4]:
b = np.array([1.2,2.4,3.5,5.6])
b

array([ 1.2,  2.4,  3.5,  5.6])

In [5]:
b.dtype

dtype('float64')

In [6]:
# You can still type comments like this one.

In [8]:
#2d arrays (Like a table)
c = np.array([(1,2,3), (4,5,6), (7,8,9)])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
sequence = np.arange(0,100,10)
sequence

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
#Basic operations

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b

array([ 1.2,  2.4,  3.5,  5.6])

In [14]:
a-b

array([-0.2, -0.4, -0.5, -1.6])

In [16]:
a+b

array([ 2.2,  4.4,  6.5,  9.6])

In [18]:
a*2

array([2, 4, 6, 8])

In [19]:
a**3

array([ 1,  8, 27, 64])

In [20]:
a<2

array([ True, False, False, False], dtype=bool)

In [21]:
a = a+b
a

array([ 2.2,  4.4,  6.5,  9.6])

In [22]:
a.sum()

22.700000000000003

In [23]:
a.min()

2.2000000000000002

In [24]:
a.max()

9.5999999999999996

In [25]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#Sum all of the numbers
c.sum()

45

In [27]:
#Sum along the columns
c.sum(axis=0)

array([12, 15, 18])

In [28]:
#Sum along the rows
c.sum(axis=1)

array([ 6, 15, 24])

In [30]:
#Min/Max on rows
c.min(axis=1)

array([1, 4, 7])

In [35]:
#Simple Indexing and Slicing

In [36]:
a[1]

4.4000000000000004

In [38]:
a

array([ 2.2,  4.4,  6.5,  9.6])

In [39]:
a[1:]

array([ 4.4,  6.5,  9.6])

In [40]:
a[:3]

array([ 2.2,  4.4,  6.5])

In [41]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
c[0,0:3]

array([1, 2, 3])

In [48]:
c[0:3, 0]

array([1, 4, 7])